export const all_articles = [
  {
    id: '1',
    title: 'How To Use Unsupervised Learning With Python To Find Patterns In Data',
    desc: "A beginner's guide to unsupervised learning in Python",
    url: 'https://builtin.com/data-science/unsupervised-learning-python',
    published_on: 'June 7, 2019',
    published_at: 'BuiltIn',
    views: '',
    tags: ['data-science', 'python'],
    pinned: 'false',
    borderColor: '',
    extra: ''
  },
  {
    id: '2',
    title: 'Reinforcement Learning With Python: A Guide To Designing And Solving Problems',
    desc: "A beginner's guide to unsupervised learning in Python",
    url: 'https://builtin.com/data-science/reinforcement-learning-python',
    published_on: 'June 7, 2019',
    published_at: 'BuiltIn',
    views: '',
    tags: ['data-science', 'python'],
    pinned: 'false',
    extra: ''
  },
  {
    id: '3',
    title: 'An Introduction To Machine Learning For Beginners',
    desc: 'What is machine learning? How does it work? How much math is involved?',
    url: 'https://builtin.com/data-science/introduction-to-machine-learning',
    published_on: 'June 7, 2019',
    published_at: 'BuiltIn',
    views: '',
    tags: ['machine-learning', 'intro'],
    pinned: '',
    extra: ''
  },
  {
    id: '4',
    title: 'Implementing Python in Deep Learning: An In-Depth Guide',
    desc: 'Imitating the human brain using one of the most popular programming languages, Python.',
    url: 'https://builtin.com/data-science/deep-learning-python',
    published_on: 'June 7, 2019',
    published_at: 'BuiltIn',
    views: '',
    tags: ['deep-learning', 'python'],
    pinned: '',
    extra: ''
  },
  {
    id: '5',
    title: "A Beginner's Guide To Supervised Learning With Python",
    desc: "The ultimate goal of the supervised learning algorithm is to predict Y with the max accuracy for a given new input X. Here's how that works.",
    url: 'https://builtin.com/data-science/supervised-learning-python',
    published_on: 'June 7, 2019',
    published_at: 'BuiltIn',
    views: '',
    tags: ['data-science', 'python'],
    pinned: '',
    extra: ''
  },
  {
    id: '6',
    title: 'A Guide to Logistic Regression with Tensorflow 2.0',
    desc: 'An in-depth look at logistic regression analysis with TensorFlow 2.0',
    url: 'https://builtin.com/data-science/guide-logistic-regression-tensorflow-20',
    published_on: 'April 28, 2020',
    published_at: 'BuiltIn',
    views: '',
    tags: ['deep-learning', 'python'],
    pinned: '',
    extra: ''
  },
  {
    id: '7',
    title: '3D RENDERING USING THREE.JS',
    desc: 'A step-by-step guide to rotating a 3D cube with three.js and a challenge for the reader.',
    url: 'https://builtin.com/expert-contributors-software-engineering-perspectives/3d-rendering-using-threejs',
    published_on: 'April 16, 2020',
    published_at: 'BuiltIn',
    views: '',
    tags: ['javascript', 'graphics'],
    pinned: '',
    extra: ''
  },
  {
    id: '8',
    title: 'A Quick Introduction to Segmentation, Correlation and Time Series MODELING',
    desc: 'Choosing the right algorithm for modeling data is a crucial part of the work of a data scientist. Here are the basic techniques.',
    url: 'https://builtin.com/data-science/introduction-segmentation-correlation-time-series-modeling',
    published_on: 'April 9, 2020',
    published_at: 'BuiltIn',
    views: '',
    tags: ['data-science', 'python'],
    pinned: '',
    extra: ''
  },
  {
    id: '9',
    title: 'PYTORCH VS. TENSORFLOW: Which Framework is best for your deep learning project?',
    desc: '',
    url: 'https://builtin.com/data-science/pytorch-vs-tensorflow',
    published_on: 'September 19, 2020',
    published_at: 'BuiltIn',
    views: '',
    tags: ['deep-learning', 'python'],
    pinned: '',
    extra: ''
  },
  {
    id: '10',
    title: 'Linear Regression: Concepts and Applications with Tensorflow 2.0',
    desc: 'An in-depth look at linear regression analysis with TensorFlow 2.0',
    url: 'https://builtin.com/data-science/linear-regression-tensorflow',
    published_on: 'April 24, 2020',
    published_at: 'BuiltIn',
    views: '',
    tags: ['deep-learning', 'python'],
    pinned: '',
    extra: ''
  },
  {
    id: '11',
    title: 'Convolution Neural Networks Explained: Using PyTorch',
    desc: "Beginner's guide to CNN's",
    url: 'https://builtin.com/data-science/introduction-segmentation-correlation-time-series-modeling',
    published_on: 'Aug 19, 2020',
    published_at: 'BuiltIn',
    views: '',
    tags: ['deep-learning', 'python'],
    pinned: '',
    extra: ''
  },
  {
    id: '12',
    title: 'A QUICK PRIMER ON FEEDFORWARD NEURAL NETWORKS',
    desc: '',
    url: 'https://builtin.com/data-science/feedforward-neural-network-intro',
    published_on: 'September 4, 2019',
    published_at: 'BuiltIn',
    views: '',
    tags: ['deep-learning', 'python'],
    pinned: '',
    extra: ''
  },
  {
    id: '13',
    title: 'REGRESSION IN MACHINE LEARNING: WHAT IT IS AND EXAMPLES OF DIFFERENT MODELS',
    desc: 'The ultimate goal of the regression algorithm is to plot a best-fit line or a curve between the data.',
    url: 'https://builtin.com/data-science/regression-machine-learning',
    published_on: 'September 4, 2019',
    published_at: 'BuiltIn',
    views: '',
    tags: ['machine-learning', 'guide'],
    pinned: '',
    extra: ''
  },
  {
    id: '14',
    title: "Beginner's Guide to Boltzmann Machines in PyTorch",
    desc: '',
    url: 'https://blog.paperspace.com/beginners-guide-to-boltzmann-machines-pytorch',
    published_on: 'November 20, 2020',
    published_at: 'Paperspace',
    views: '',
    tags: ['machine-learning', 'pytorch'],
    pinned: '',
    extra: ''
  },
  {
    id: '15',
    title: 'A Comprehensive Guide to the DataLoader Class and Abstractions in PyTorch',
    desc: '',
    url: 'https://blog.paperspace.com/dataloaders-abstractions-pytorch/',
    published_on: 'November 27, 2020',
    published_at: 'Paperspace',
    views: '',
    tags: ['machine-learning', 'pytorch'],
    pinned: '',
    extra: ''
  },
  {
    id: '16',
    title: 'How JavaScript Libraries Are Training Neural Networks on Web Browsers',
    desc: '',
    url: 'https://blog.paperspace.com/javascript-deep-learning-on-web-browsers',
    published_on: 'January 7, 2021',
    published_at: 'Paperspace',
    views: '',
    tags: ['deep-learning', 'tensorflow'],
    pinned: '',
    extra: ''
  },
  {
    id: '17',
    title: 'Capsule Networks: A Quick Primer',
    desc: '',
    url: 'https://blog.paperspace.com/capsule-networks/',
    published_on: 'July 7 2020',
    published_at: 'Paperspace',
    views: '',
    tags: ['deep-learning', 'guide'],
    pinned: '',
    extra: ''
  },
  {
    id: '18',
    title: 'DL Architectures Review: DenseNet, ResNeXt, MnasNet, and ShuffleNet v2',
    desc: '',
    url: 'https://blog.paperspace.com/popular-deep-learning-architectures-densenet-mnasnet-shufflenet',
    published_on: 'July 22 2020',
    published_at: 'Paperspace',
    views: '',
    tags: ['deep-learning', 'review'],
    pinned: '',
    extra: ''
  },
  {
    id: '19',
    title: 'DL Architectures Review: ResNet, InceptionV3, and SqueezeNet',
    desc: '',
    url: 'https://blog.paperspace.com/popular-deep-learning-architectures-resnet-inceptionv3-squeezenet/',
    published_on: 'July 7 2020',
    published_at: 'Paperspace',
    views: '',
    tags: ['deep-learning', 'review'],
    pinned: '',
    extra: ''
  },
  {
    id: '20',
    title: 'DL Architectures Review: AlexNet, VGG16, and GoogleNet',
    desc: '',
    url: 'https://blog.paperspace.com/popular-deep-learning-architectures-alexnet-vgg-googlenet/',
    published_on: 'July 7 2020',
    published_at: 'Paperspace',
    views: '',
    tags: ['deep-learning', 'review'],
    pinned: '',
    extra: ''
  },
  {
    id: '21',
    title: 'Fighting COVID-19 with Data and AI: A Review of Active Research Groups and Datasets',
    desc: '',
    url: 'https://blog.paperspace.com/fighting-covid-19-using-artificial-intelligence-and-data/',
    published_on: 'April 9 2020',
    published_at: 'Paperspace',
    views: '',
    tags: ['deep-learning', 'covid19'],
    pinned: '',
    extra: ''
  },
  {
    id: '22',
    title: 'A Guide To Random Forests: Consolidating Decision Trees',
    desc: '',
    url: 'https://blog.paperspace.com/random-forests/',
    published_on: 'Feb 16, 2020',
    published_at: 'Paperspace',
    views: '',
    tags: ['machine-learning', 'python'],
    pinned: '',
    extra: ''
  },
  {
    id: '23',
    title: 'An Introduction to Decision Trees',
    desc: '',
    url: 'https://blog.paperspace.com/decision-trees/',
    published_on: 'Feb 14, 2020',
    published_at: 'Paperspace',
    views: '',
    tags: ['machine-learning', 'python'],
    pinned: '',
    extra: ''
  },
  {
    id: '24',
    title: 'Introduction to Bagging and Ensemble Methods',
    desc: '',
    url: 'https://blog.paperspace.com/bagging-ensemble-methods/',
    published_on: 'Jan 13, 2020',
    published_at: 'Paperspace',
    views: '',
    tags: ['machine-learning', 'python'],
    pinned: '',
    extra: ''
  },
  {
    id: '25',
    title: 'Deploying Deep Learning Models Part 2: Hosting on Paperspace[1]',
    desc: '',
    url: 'https://blog.paperspace.com/deploying-deep-learning-models-flask-web-python/',
    published_on: 'April 5, 2020',
    published_at: 'Paperspace',
    views: '',
    tags: ['deep-learning', 'python'],
    pinned: '',
    extra: ''
  },
  {
    id: '26',
    title: 'Deploying Deep Learning Models Part 2: Hosting on Paperspace[2]',
    desc: '',
    url: 'https://blog.paperspace.com/deploying-deep-learning-models-part-ii-hosting-on-paperspace/',
    published_on: 'April 4, 2020',
    published_at: 'Paperspace',
    views: '',
    tags: ['deep-learning', 'python'],
    pinned: '',
    extra: ''
  },
  {
    id: '26',
    title: 'A Guide to AdaBoost: Boosting To Save The Day',
    desc: '',
    url: 'https://blog.paperspace.com/adaboost-optimizer/',
    published_on: 'May 29, 2020',
    published_at: 'Paperspace',
    views: '',
    tags: ['machine-learning', 'python'],
    pinned: '',
    extra: ''
  },
  {
    id: '27',
    title: 'Gradient Boosting In Classification: Not a Black Box Anymore!',
    desc: '',
    url: 'https://blog.paperspace.com/gradient-boosting-for-classification/',
    published_on: 'June 3, 2020',
    published_at: 'Paperspace',
    views: '',
    tags: ['machine-learning', 'python'],
    pinned: '',
    extra: ''
  },
  {
    id: '28',
    title: '  Introduction to Naive Bayes: A Probability-Based Classification Algorithm',
    desc: '',
    url: 'https://blog.paperspace.com/introduction-to-naive-bayes/',
    published_on: 'June 14, 2020',
    published_at: 'Paperspace',
    views: '',
    tags: ['machine-learning', 'python'],
    pinned: '',
    extra: ''
  }
];
